name: WorkPart CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Git config user
        run: |
          git config --local user.email "manuelnavarro1987@gmail.com"
          git config --local user.name "i62navpm"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create release
        run: npx lerna version -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
